# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: yarn-format
        name: run yarn format
        language: system
        entry: bash -c 'cd www && yarn format'
        pass_filenames: false
        files: ^www/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
        exclude: ^server/trials
      - id: detect-private-key

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        files: ^server/(reflector|tests)/

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: ^server/(reflector|tests)/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        files: ^server/(gpu|evaluate|reflector)/
