/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateParticipant
 */
export interface CreateParticipant {
  /**
   *
   * @type {any}
   * @memberof CreateParticipant
   */
  speaker?: any | null;
  /**
   *
   * @type {any}
   * @memberof CreateParticipant
   */
  name: any | null;
}

/**
 * Check if a given object implements the CreateParticipant interface.
 */
export function instanceOfCreateParticipant(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "name" in value;

  return isInstance;
}

export function CreateParticipantFromJSON(json: any): CreateParticipant {
  return CreateParticipantFromJSONTyped(json, false);
}

export function CreateParticipantFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateParticipant {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    speaker: !exists(json, "speaker") ? undefined : json["speaker"],
    name: json["name"],
  };
}

export function CreateParticipantToJSON(value?: CreateParticipant | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    speaker: value.speaker,
    name: value.name,
  };
}
