/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateTranscript
 */
export interface CreateTranscript {
  /**
   *
   * @type {any}
   * @memberof CreateTranscript
   */
  name: any | null;
  /**
   *
   * @type {any}
   * @memberof CreateTranscript
   */
  sourceLanguage?: any | null;
  /**
   *
   * @type {any}
   * @memberof CreateTranscript
   */
  targetLanguage?: any | null;
}

/**
 * Check if a given object implements the CreateTranscript interface.
 */
export function instanceOfCreateTranscript(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "name" in value;

  return isInstance;
}

export function CreateTranscriptFromJSON(json: any): CreateTranscript {
  return CreateTranscriptFromJSONTyped(json, false);
}

export function CreateTranscriptFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTranscript {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    sourceLanguage: !exists(json, "source_language")
      ? undefined
      : json["source_language"],
    targetLanguage: !exists(json, "target_language")
      ? undefined
      : json["target_language"],
  };
}

export function CreateTranscriptToJSON(value?: CreateTranscript | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    source_language: value.sourceLanguage,
    target_language: value.targetLanguage,
  };
}
