/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DeletionStatus
 */
export interface DeletionStatus {
  /**
   *
   * @type {any}
   * @memberof DeletionStatus
   */
  status: any | null;
}

/**
 * Check if a given object implements the DeletionStatus interface.
 */
export function instanceOfDeletionStatus(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "status" in value;

  return isInstance;
}

export function DeletionStatusFromJSON(json: any): DeletionStatus {
  return DeletionStatusFromJSONTyped(json, false);
}

export function DeletionStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeletionStatus {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: json["status"],
  };
}

export function DeletionStatusToJSON(value?: DeletionStatus | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: value.status,
  };
}
