/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetTranscriptSegmentTopic
 */
export interface GetTranscriptSegmentTopic {
  /**
   *
   * @type {any}
   * @memberof GetTranscriptSegmentTopic
   */
  text: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptSegmentTopic
   */
  start: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptSegmentTopic
   */
  speaker: any | null;
}

/**
 * Check if a given object implements the GetTranscriptSegmentTopic interface.
 */
export function instanceOfGetTranscriptSegmentTopic(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "text" in value;
  isInstance = isInstance && "start" in value;
  isInstance = isInstance && "speaker" in value;

  return isInstance;
}

export function GetTranscriptSegmentTopicFromJSON(
  json: any,
): GetTranscriptSegmentTopic {
  return GetTranscriptSegmentTopicFromJSONTyped(json, false);
}

export function GetTranscriptSegmentTopicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTranscriptSegmentTopic {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    text: json["text"],
    start: json["start"],
    speaker: json["speaker"],
  };
}

export function GetTranscriptSegmentTopicToJSON(
  value?: GetTranscriptSegmentTopic | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    text: value.text,
    start: value.start,
    speaker: value.speaker,
  };
}
