/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetTranscript
 */
export interface GetTranscript {
  /**
   *
   * @type {any}
   * @memberof GetTranscript
   */
  id: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscript
   */
  name: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscript
   */
  status: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscript
   */
  locked: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscript
   */
  duration: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscript
   */
  createdAt: any | null;
}

/**
 * Check if a given object implements the GetTranscript interface.
 */
export function instanceOfGetTranscript(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "locked" in value;
  isInstance = isInstance && "duration" in value;
  isInstance = isInstance && "createdAt" in value;

  return isInstance;
}

export function GetTranscriptFromJSON(json: any): GetTranscript {
  return GetTranscriptFromJSONTyped(json, false);
}

export function GetTranscriptFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTranscript {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    status: json["status"],
    locked: json["locked"],
    duration: json["duration"],
    createdAt: json["created_at"],
  };
}

export function GetTranscriptToJSON(value?: GetTranscript | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    status: value.status,
    locked: value.locked,
    duration: value.duration,
    created_at: value.createdAt,
  };
}
