/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetTranscriptTopicWithWords
 */
export interface GetTranscriptTopicWithWords {
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWords
   */
  id: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWords
   */
  title: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWords
   */
  summary: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWords
   */
  timestamp: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWords
   */
  transcript: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWords
   */
  segments?: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWords
   */
  words?: any | null;
}

/**
 * Check if a given object implements the GetTranscriptTopicWithWords interface.
 */
export function instanceOfGetTranscriptTopicWithWords(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "title" in value;
  isInstance = isInstance && "summary" in value;
  isInstance = isInstance && "timestamp" in value;
  isInstance = isInstance && "transcript" in value;

  return isInstance;
}

export function GetTranscriptTopicWithWordsFromJSON(
  json: any,
): GetTranscriptTopicWithWords {
  return GetTranscriptTopicWithWordsFromJSONTyped(json, false);
}

export function GetTranscriptTopicWithWordsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTranscriptTopicWithWords {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    summary: json["summary"],
    timestamp: json["timestamp"],
    transcript: json["transcript"],
    segments: !exists(json, "segments") ? undefined : json["segments"],
    words: !exists(json, "words") ? undefined : json["words"],
  };
}

export function GetTranscriptTopicWithWordsToJSON(
  value?: GetTranscriptTopicWithWords | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    summary: value.summary,
    timestamp: value.timestamp,
    transcript: value.transcript,
    segments: value.segments,
    words: value.words,
  };
}
