/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetTranscriptTopicWithWordsPerSpeaker
 */
export interface GetTranscriptTopicWithWordsPerSpeaker {
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWordsPerSpeaker
   */
  id: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWordsPerSpeaker
   */
  title: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWordsPerSpeaker
   */
  summary: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWordsPerSpeaker
   */
  timestamp: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWordsPerSpeaker
   */
  duration: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWordsPerSpeaker
   */
  transcript: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWordsPerSpeaker
   */
  segments?: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopicWithWordsPerSpeaker
   */
  wordsPerSpeaker?: any | null;
}

/**
 * Check if a given object implements the GetTranscriptTopicWithWordsPerSpeaker interface.
 */
export function instanceOfGetTranscriptTopicWithWordsPerSpeaker(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "title" in value;
  isInstance = isInstance && "summary" in value;
  isInstance = isInstance && "timestamp" in value;
  isInstance = isInstance && "duration" in value;
  isInstance = isInstance && "transcript" in value;

  return isInstance;
}

export function GetTranscriptTopicWithWordsPerSpeakerFromJSON(
  json: any,
): GetTranscriptTopicWithWordsPerSpeaker {
  return GetTranscriptTopicWithWordsPerSpeakerFromJSONTyped(json, false);
}

export function GetTranscriptTopicWithWordsPerSpeakerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTranscriptTopicWithWordsPerSpeaker {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    summary: json["summary"],
    timestamp: json["timestamp"],
    duration: json["duration"],
    transcript: json["transcript"],
    segments: !exists(json, "segments") ? undefined : json["segments"],
    wordsPerSpeaker: !exists(json, "words_per_speaker")
      ? undefined
      : json["words_per_speaker"],
  };
}

export function GetTranscriptTopicWithWordsPerSpeakerToJSON(
  value?: GetTranscriptTopicWithWordsPerSpeaker | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    summary: value.summary,
    timestamp: value.timestamp,
    duration: value.duration,
    transcript: value.transcript,
    segments: value.segments,
    words_per_speaker: value.wordsPerSpeaker,
  };
}
