/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetTranscriptTopic
 */
export interface GetTranscriptTopic {
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopic
   */
  title: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopic
   */
  summary: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopic
   */
  timestamp: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopic
   */
  text: any | null;
  /**
   *
   * @type {any}
   * @memberof GetTranscriptTopic
   */
  segments?: any | null;
}

/**
 * Check if a given object implements the GetTranscriptTopic interface.
 */
export function instanceOfGetTranscriptTopic(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "title" in value;
  isInstance = isInstance && "summary" in value;
  isInstance = isInstance && "timestamp" in value;
  isInstance = isInstance && "text" in value;

  return isInstance;
}

export function GetTranscriptTopicFromJSON(json: any): GetTranscriptTopic {
  return GetTranscriptTopicFromJSONTyped(json, false);
}

export function GetTranscriptTopicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTranscriptTopic {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: json["title"],
    summary: json["summary"],
    timestamp: json["timestamp"],
    text: json["text"],
    segments: !exists(json, "segments") ? undefined : json["segments"],
  };
}

export function GetTranscriptTopicToJSON(
  value?: GetTranscriptTopic | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    summary: value.summary,
    timestamp: value.timestamp,
    text: value.text,
    segments: value.segments,
  };
}
