/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PageGetTranscript
 */
export interface PageGetTranscript {
  /**
   *
   * @type {any}
   * @memberof PageGetTranscript
   */
  items: any | null;
  /**
   *
   * @type {any}
   * @memberof PageGetTranscript
   */
  total: any | null;
  /**
   *
   * @type {any}
   * @memberof PageGetTranscript
   */
  page: any | null;
  /**
   *
   * @type {any}
   * @memberof PageGetTranscript
   */
  size: any | null;
  /**
   *
   * @type {any}
   * @memberof PageGetTranscript
   */
  pages?: any | null;
}

/**
 * Check if a given object implements the PageGetTranscript interface.
 */
export function instanceOfPageGetTranscript(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "items" in value;
  isInstance = isInstance && "total" in value;
  isInstance = isInstance && "page" in value;
  isInstance = isInstance && "size" in value;

  return isInstance;
}

export function PageGetTranscriptFromJSON(json: any): PageGetTranscript {
  return PageGetTranscriptFromJSONTyped(json, false);
}

export function PageGetTranscriptFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PageGetTranscript {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    items: json["items"],
    total: json["total"],
    page: json["page"],
    size: json["size"],
    pages: !exists(json, "pages") ? undefined : json["pages"],
  };
}

export function PageGetTranscriptToJSON(value?: PageGetTranscript | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    items: value.items,
    total: value.total,
    page: value.page,
    size: value.size,
    pages: value.pages,
  };
}
