/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RtcOffer
 */
export interface RtcOffer {
  /**
   *
   * @type {any}
   * @memberof RtcOffer
   */
  sdp: any | null;
  /**
   *
   * @type {any}
   * @memberof RtcOffer
   */
  type: any | null;
}

/**
 * Check if a given object implements the RtcOffer interface.
 */
export function instanceOfRtcOffer(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "sdp" in value;
  isInstance = isInstance && "type" in value;

  return isInstance;
}

export function RtcOfferFromJSON(json: any): RtcOffer {
  return RtcOfferFromJSONTyped(json, false);
}

export function RtcOfferFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RtcOffer {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    sdp: json["sdp"],
    type: json["type"],
  };
}

export function RtcOfferToJSON(value?: RtcOffer | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    sdp: value.sdp,
    type: value.type,
  };
}
