/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SpeakerMerge
 */
export interface SpeakerMerge {
  /**
   *
   * @type {any}
   * @memberof SpeakerMerge
   */
  speakerFrom: any | null;
  /**
   *
   * @type {any}
   * @memberof SpeakerMerge
   */
  speakerTo: any | null;
}

/**
 * Check if a given object implements the SpeakerMerge interface.
 */
export function instanceOfSpeakerMerge(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "speakerFrom" in value;
  isInstance = isInstance && "speakerTo" in value;

  return isInstance;
}

export function SpeakerMergeFromJSON(json: any): SpeakerMerge {
  return SpeakerMergeFromJSONTyped(json, false);
}

export function SpeakerMergeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SpeakerMerge {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    speakerFrom: json["speaker_from"],
    speakerTo: json["speaker_to"],
  };
}

export function SpeakerMergeToJSON(value?: SpeakerMerge | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    speaker_from: value.speakerFrom,
    speaker_to: value.speakerTo,
  };
}
