/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SpeakerAssignmentStatus
 */
export interface SpeakerAssignmentStatus {
  /**
   *
   * @type {any}
   * @memberof SpeakerAssignmentStatus
   */
  status: any | null;
}

/**
 * Check if a given object implements the SpeakerAssignmentStatus interface.
 */
export function instanceOfSpeakerAssignmentStatus(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "status" in value;

  return isInstance;
}

export function SpeakerAssignmentStatusFromJSON(
  json: any,
): SpeakerAssignmentStatus {
  return SpeakerAssignmentStatusFromJSONTyped(json, false);
}

export function SpeakerAssignmentStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SpeakerAssignmentStatus {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: json["status"],
  };
}

export function SpeakerAssignmentStatusToJSON(
  value?: SpeakerAssignmentStatus | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: value.status,
  };
}
