/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SpeakerWords
 */
export interface SpeakerWords {
  /**
   *
   * @type {any}
   * @memberof SpeakerWords
   */
  speaker: any | null;
  /**
   *
   * @type {any}
   * @memberof SpeakerWords
   */
  words: any | null;
}

/**
 * Check if a given object implements the SpeakerWords interface.
 */
export function instanceOfSpeakerWords(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "speaker" in value;
  isInstance = isInstance && "words" in value;

  return isInstance;
}

export function SpeakerWordsFromJSON(json: any): SpeakerWords {
  return SpeakerWordsFromJSONTyped(json, false);
}

export function SpeakerWordsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SpeakerWords {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    speaker: json["speaker"],
    words: json["words"],
  };
}

export function SpeakerWordsToJSON(value?: SpeakerWords | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    speaker: value.speaker,
    words: value.words,
  };
}
