/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TranscriptParticipant
 */
export interface TranscriptParticipant {
  /**
   *
   * @type {any}
   * @memberof TranscriptParticipant
   */
  id?: any | null;
  /**
   *
   * @type {any}
   * @memberof TranscriptParticipant
   */
  speaker: any | null;
  /**
   *
   * @type {any}
   * @memberof TranscriptParticipant
   */
  name: any | null;
}

/**
 * Check if a given object implements the TranscriptParticipant interface.
 */
export function instanceOfTranscriptParticipant(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "speaker" in value;
  isInstance = isInstance && "name" in value;

  return isInstance;
}

export function TranscriptParticipantFromJSON(
  json: any,
): TranscriptParticipant {
  return TranscriptParticipantFromJSONTyped(json, false);
}

export function TranscriptParticipantFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TranscriptParticipant {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    speaker: json["speaker"],
    name: json["name"],
  };
}

export function TranscriptParticipantToJSON(
  value?: TranscriptParticipant | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    speaker: value.speaker,
    name: value.name,
  };
}
