/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TranscriptTopic
 */
export interface TranscriptTopic {
  /**
   *
   * @type {any}
   * @memberof TranscriptTopic
   */
  id?: any | null;
  /**
   *
   * @type {any}
   * @memberof TranscriptTopic
   */
  title: any | null;
  /**
   *
   * @type {any}
   * @memberof TranscriptTopic
   */
  summary: any | null;
  /**
   *
   * @type {any}
   * @memberof TranscriptTopic
   */
  transcript: any | null;
  /**
   *
   * @type {any}
   * @memberof TranscriptTopic
   */
  timestamp: any | null;
}

/**
 * Check if a given object implements the TranscriptTopic interface.
 */
export function instanceOfTranscriptTopic(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "title" in value;
  isInstance = isInstance && "summary" in value;
  isInstance = isInstance && "transcript" in value;
  isInstance = isInstance && "timestamp" in value;

  return isInstance;
}

export function TranscriptTopicFromJSON(json: any): TranscriptTopic {
  return TranscriptTopicFromJSONTyped(json, false);
}

export function TranscriptTopicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TranscriptTopic {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    title: json["title"],
    summary: json["summary"],
    transcript: json["transcript"],
    timestamp: json["timestamp"],
  };
}

export function TranscriptTopicToJSON(value?: TranscriptTopic | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    summary: value.summary,
    transcript: value.transcript,
    timestamp: value.timestamp,
  };
}
