/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TranscriptSegmentTopic
 */
export interface TranscriptSegmentTopic {
  /**
   *
   * @type {any}
   * @memberof TranscriptSegmentTopic
   */
  speaker: any | null;
  /**
   *
   * @type {any}
   * @memberof TranscriptSegmentTopic
   */
  text: any | null;
  /**
   *
   * @type {any}
   * @memberof TranscriptSegmentTopic
   */
  timestamp: any | null;
}

/**
 * Check if a given object implements the TranscriptSegmentTopic interface.
 */
export function instanceOfTranscriptSegmentTopic(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "speaker" in value;
  isInstance = isInstance && "text" in value;
  isInstance = isInstance && "timestamp" in value;

  return isInstance;
}

export function TranscriptSegmentTopicFromJSON(
  json: any,
): TranscriptSegmentTopic {
  return TranscriptSegmentTopicFromJSONTyped(json, false);
}

export function TranscriptSegmentTopicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TranscriptSegmentTopic {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    speaker: json["speaker"],
    text: json["text"],
    timestamp: json["timestamp"],
  };
}

export function TranscriptSegmentTopicToJSON(
  value?: TranscriptSegmentTopic | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    speaker: value.speaker,
    text: value.text,
    timestamp: value.timestamp,
  };
}
