/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateTranscript
 */
export interface UpdateTranscript {
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  name?: any | null;
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  locked?: any | null;
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  title?: any | null;
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  shortSummary?: any | null;
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  longSummary?: any | null;
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  shareMode?: any | null;
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  participants?: any | null;
}

/**
 * Check if a given object implements the UpdateTranscript interface.
 */
export function instanceOfUpdateTranscript(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateTranscriptFromJSON(json: any): UpdateTranscript {
  return UpdateTranscriptFromJSONTyped(json, false);
}

export function UpdateTranscriptFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateTranscript {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    locked: !exists(json, "locked") ? undefined : json["locked"],
    title: !exists(json, "title") ? undefined : json["title"],
    shortSummary: !exists(json, "short_summary")
      ? undefined
      : json["short_summary"],
    longSummary: !exists(json, "long_summary")
      ? undefined
      : json["long_summary"],
    shareMode: !exists(json, "share_mode") ? undefined : json["share_mode"],
    participants: !exists(json, "participants")
      ? undefined
      : json["participants"],
  };
}

export function UpdateTranscriptToJSON(value?: UpdateTranscript | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    locked: value.locked,
    title: value.title,
    short_summary: value.shortSummary,
    long_summary: value.longSummary,
    share_mode: value.shareMode,
    participants: value.participants,
  };
}
