/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateParticipant
 */
export interface UpdateParticipant {
  /**
   *
   * @type {any}
   * @memberof UpdateParticipant
   */
  speaker?: any | null;
  /**
   *
   * @type {any}
   * @memberof UpdateParticipant
   */
  name?: any | null;
}

/**
 * Check if a given object implements the UpdateParticipant interface.
 */
export function instanceOfUpdateParticipant(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateParticipantFromJSON(json: any): UpdateParticipant {
  return UpdateParticipantFromJSONTyped(json, false);
}

export function UpdateParticipantFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateParticipant {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    speaker: !exists(json, "speaker") ? undefined : json["speaker"],
    name: !exists(json, "name") ? undefined : json["name"],
  };
}

export function UpdateParticipantToJSON(value?: UpdateParticipant | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    speaker: value.speaker,
    name: value.name,
  };
}
