/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateTranscript
 */
export interface UpdateTranscript {
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  name?: any | null;
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  locked?: any | null;
  /**
   *
   * @type {any}
   * @memberof UpdateTranscript
   */
  summary?: any | null;
}

/**
 * Check if a given object implements the UpdateTranscript interface.
 */
export function instanceOfUpdateTranscript(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateTranscriptFromJSON(json: any): UpdateTranscript {
  return UpdateTranscriptFromJSONTyped(json, false);
}

export function UpdateTranscriptFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateTranscript {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    locked: !exists(json, "locked") ? undefined : json["locked"],
    summary: !exists(json, "summary") ? undefined : json["summary"],
  };
}

export function UpdateTranscriptToJSON(value?: UpdateTranscript | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    locked: value.locked,
    summary: value.summary,
  };
}
