version: "3.9"
services:
  server:
    build:
      context: .
    ports:
      - 1250:1250
    environment:
      LLM_URL: "${LLM_URL}"
    volumes:
      - model-cache:/root/.cache

volumes:
  model-cache:
