version: "3.9"
services:
  server:
    build:
      context: .
    ports:
      - 1250:1250
    volumes:
      - model-cache:/root/.cache
    environment:
      ENTRYPOINT: server
      REDIS_HOST: redis
  worker:
    build:
      context: .
    volumes:
      - model-cache:/root/.cache
    environment:
      ENTRYPOINT: worker
      REDIS_HOST: redis
  redis:
    image: redis:7.2
    ports:
      - 6379:6379

volumes:
  model-cache:
