version: "3.9"
services:
  # server:
  #   build:
  #     context: .
  #   ports:
  #     - 1250:1250
  #   environment:
  #     LLM_URL: "${LLM_URL}"
  #     MIN_TRANSCRIPT_LENGTH: "${MIN_TRANSCRIPT_LENGTH}"
  #   volumes:
  #     - model-cache:/root/.cache
  redis:
    image: redis:7.2
    ports:
      - 6379:6379

volumes:
  model-cache:
