"""add cascade delete to meeting consent fk

Revision ID: 33292043ceed
Revises: b5e7b4e94672
Create Date: 2025-08-26 12:13:18.740722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33292043ceed'
down_revision: Union[str, None] = 'b5e7b4e94672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_consent', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('meeting_consent_meeting_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'meeting', ['meeting_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_consent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('meeting_consent_meeting_id_fkey'), 'meeting', ['meeting_id'], ['id'])

    # ### end Alembic commands ###
