"""add room options

Revision ID: 62dea3db63a5
Revises: 1340c04426b8
Create Date: 2025-06-27 09:04:21.006823

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62dea3db63a5"
down_revision: Union[str, None] = "1340c04426b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meeting",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("room_name", sa.String(), nullable=True),
        sa.Column("room_url", sa.String(), nullable=True),
        sa.Column("host_room_url", sa.String(), nullable=True),
        sa.Column("viewer_room_url", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("room_id", sa.String(), nullable=True),
        sa.Column(
            "is_locked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("room_mode", sa.String(), server_default="normal", nullable=False),
        sa.Column(
            "recording_type", sa.String(), server_default="cloud", nullable=False
        ),
        sa.Column(
            "recording_trigger",
            sa.String(),
            server_default="automatic-2nd-participant",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "room",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "zulip_auto_post",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("zulip_stream", sa.String(), nullable=True),
        sa.Column("zulip_topic", sa.String(), nullable=True),
        sa.Column(
            "is_locked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("room_mode", sa.String(), server_default="normal", nullable=False),
        sa.Column(
            "recording_type", sa.String(), server_default="cloud", nullable=False
        ),
        sa.Column(
            "recording_trigger",
            sa.String(),
            server_default="automatic-2nd-participant",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room")
    op.drop_table("meeting")
    # ### end Alembic commands ###
