"""set default value for platform

Revision ID: 6305691d2ba7
Revises: f8294b31f022
Create Date: 2025-11-12 20:54:19.927991

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6305691d2ba7"
down_revision: Union[str, None] = "f8294b31f022"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update all NULL values to 'whereby'
    op.execute("UPDATE room SET platform = 'whereby' WHERE platform IS NULL")

    # Then set server default for platform column to 'whereby' and make it NOT NULL
    op.alter_column(
        "room",
        "platform",
        existing_type=sa.String(),
        server_default="whereby",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove server default from platform column
    op.alter_column(
        "room",
        "platform",
        existing_type=sa.String(),
        server_default=None,
        nullable=True,
    )
    # ### end Alembic commands ###
