"""sync schemas

Revision ID: 9365e8b46fee
Revises: 20250618140000
Create Date: 2025-06-27 09:28:55.070815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9365e8b46fee"
down_revision: Union[str, None] = "20250618140000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting_consent", schema=None) as batch_op:
        batch_op.alter_column("meeting_id", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "consent_given", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "consent_timestamp", existing_type=sa.DATETIME(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting_consent", schema=None) as batch_op:
        batch_op.alter_column(
            "consent_timestamp", existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.alter_column(
            "consent_given", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column("meeting_id", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
