"""Remove viewer room url

Revision ID: b469348df210
Revises: 722e93c4ab22
Create Date: 2024-10-11 13:45:28.914902

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b469348df210"
down_revision: Union[str, None] = "722e93c4ab22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.drop_column("viewer_room_url")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.add_column(sa.Column("viewer_room_url", sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
