"""Add idempotency key to meetings

Revision ID: e3e6cb7b794d
Revises: dc035ff72fd5
Create Date: 2025-09-12 19:40:28.175481

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3e6cb7b794d"
down_revision: Union[str, None] = "dc035ff72fd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add idempotency_key column
    op.add_column("meeting", sa.Column("idempotency_key", sa.String(), nullable=True))

    # Create partial unique index that excludes NULL values
    op.create_index(
        "idx_meeting_idempotency",
        "meeting",
        ["room_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_meeting_idempotency", table_name="meeting")
    op.drop_column("meeting", "idempotency_key")
    # ### end Alembic commands ###
