"""restore idx_meeting_room_id index for performance

Revision ID: e5075bef8c83
Revises: 2ae3db106d4e
Create Date: 2025-09-11 23:53:52.917083

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5075bef8c83"
down_revision: Union[str, None] = "2ae3db106d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_meeting_room_id"), ["room_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_meeting_room_id"))
    # ### end Alembic commands ###
