name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "www/pnpm-lock.yaml"
      - name: Install dependencies
        run: cd www && pnpm install --frozen-lockfile
      - uses: pre-commit/action@v3.0.1
